---
title: "Configuration files"
output:
  BiocStyle::html_document
vignette: |
  %\VignetteIndexEntry{Configuration files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

There are two files that are costumizable: 

- Config.R file

- _targets.R file


# CONFIGURATION FILE: 
 
Configuration settings are controlled through the config.R file, which is automatically copied to your working directory when you load the epipe package. This means you don't need to manually download or create the configuration file—simply run: 

```{R,eval=FALSE}
library(epipe) 
```

This will place the config.R file in your working directory, where you can modify it before running the pipeline, allowing you to customize key analysis parameters to fit your research needs. 

Parameters to modify: 

The config.R file includes several sections that define key aspects of your analysis. Below are the most important sections and parameters you will need to customize. 

## Project configuration: 
These parameters define basic information about your project.  Customize them to reflect your research details. 

- Project name: Title of your project. This can be any name that represents your study (e.g., "Cancer_Methylation_Study"). 

- Author: Your name or the name of the principal investigator or researcher. 

- Description: A short description of your research or the project focus. 


## Sample sheet path:  

```{R,eval=FALSE}
 data_paths<-c(example_EPICv2=path/to/samplesheet.rds) 
```
You can change the name of ‘example_EPICv2’ to any custom name you prefer. For example:  

```{R,eval=FALSE}
data_paths<-c(my_custom_experiment=path/to/samplesheet.rds) 
```

This change does not affect the actual sample sheet or its location; it simply gives a different name to the dataset. Renaming this parameter allows you to keep track of different configuration analysis. When you make modifications in the config file, the pipeline will treat this as a new run with the updated settings. This is useful when you want to test multiple configurations or parameters, allowing you to quickly compare results from different analysis setups without confusion. 


### EXAMPLE: 

Suppose you want to test the pipeline with two different sets of parameters or sample sheets: 

1.You edit the config.R to set up one configuration with the name experiment_1: 
      
```{R,eval=FALSE}
        data_paths<-c(experiment_1=path/to/samplesheet.rds) 
```

2.You modify the parameters (e.g., change the normalization method, filter settings, etc.). 

3.Run the pipeline, and it will execute with the updated settings. After completion, you want to run the pipeline again with different parameters. 

4.To do so, modify the configuration file again, change the name to experiment_2, and adjust any parameters: 
```{R,eval=FALSE}
 data_paths<-c(experiment_2=path/to/samplesheet.rds) 
```

This will restart the pipeline with the new settings. By changing the key name (e.g., from experiment_1 to experiment_2), you effectively reset the pipeline, ensuring a fresh run from the beginning, even with different configurations. 



## IDAT folder path. 

idats_folder: Specify the path to the IDATS folder.   

If the Basename column in your sample sheet already includes the full path to the corresponding green and red IDAT files, you can set idats_folder <- NULL . This is because the sample sheet will already specify the path to the files for each sample, and there’s no need to provide a general folder path. 

## Folder paths

These parameters define the folders for storing results and intermediate analysis files. 

- results_folder: The directory where analysis outputs (e.g., DMPs, DMRs, plots) will be stored. You can change this to any folder name you prefer. 

- analysis_folder: A folder for storing intermediate data files generated during the analysis. This helps keep your directory organized. 

 

## Metadata

Define the columns in your sample sheet that contain important identifiers and group information. 

- idcol: The name of the column in the sample sheet that contains unique sample identifiers (e.g., "Sample_Name"). 

- sampGroups: The name of the column in the sample sheet that indicates the group or condition of each sample.  

 

## Normalization method:  

norm_function: The normalization method to apply to the methylation data. Options include: noob, ssnoob, swan, funn, noob_pq, noob_swan, quantile 

 

## Filters: These settings control various data filtering options. 

- remove_sex: Whether to exclude sex chromosomes from the analysis.  

- sex_prediction: Whether to predict the biological sex of samples based on methylation data.  


## Palette: This parameter defines a set of colors to be used in various visualizations, such as plots or graphs. The colors are represented in hexadecimal format. 

Pal_discrete: vector contains a sequence of color codes. 

 

## Variables for correlation analysis:  

Variables: defines which variables will be included in the correlation analysis. These could include experimental factors (variables in the sample sheet), demographic information like predictedAge or predictedSex, or cell type proportions like CD4T, NK, Bcell, etc.  

 

## PCA Variables: Define variables to be used in the principal component analysis 

- TopN: defines the number of CpGs to be considered for PCA. 

- bplots_var: define which variables will be used for B-plot visualizations. These could include experimental factors (variables in the sample sheet), demographic information like predictedAge or predictedSex, or cell type proportions like CD4T, NK, Bcell, etc. 

 

## Model Settings: specify the grouping variable and define the contrasts for differential analysis. 

- group_var: Main variable of interest, which will be used to compare groups. 

- Contrasts: If you're comparing two groups (e.g., Control vs. Treated), you can define the contrast here. If no contrast is specified, it is left as NULL. 

- covs: Additional variables that may influence the analysis (e.g., age, sex). Are included in the model to adjust for potential confounders. 

 

 

## Differential Methylation Analysis: Parameters for identifying differentially methylated positions (DMPs) and regions (DMRs). 

### Differentially Methylated Positions (DMPs) 

- mDiffDMP: Minimum methylation difference required for a position to be considered differentially methylated. 

- adjp.valueDMP: Adjusted p-value threshold for significance. It controls the false discovery rate (FDR). 

- p.valueDMP:  p-value threshold for statistical significance (in case no DMPs with the adjusted p-value threshold are found). 

 

### Differentially Methylated Positions (DMPs) 

- min.cpgDMR: Minimum number of CpG sites required to define a region as differentially methylated. 

- fdrDMR: False discovery rate threshold for DMRs. 

- mdiffDMR: Minimum methylation difference required for a region to be considered differentially methylated. 

 

 

##  Report Generation Options: Control which elements to include in your reports. 

report_colab and report_analyst: These parameters define the content of the generated reports, such as the report name, including quality control plots, correlation plots, or parameter tuning plots. Adjust these options based on your needs for the report format. 




# TARGETS FILE

The _targets.R file contains the main code for the pipeline, which includes the sequence of tasks and functions that will be executed. When you load the EPIPE package with 

```{R, eval=FALSE}
library(epipe)
```

the _targets.R file is automatically copied to your current working directory (if it's not already present). 

Notice that for running the pipeline you always need to have the _targets.R file in the currently working directory.  

The _targets.R file is fully customizable, allowing you to tailor the pipeline to your specific needs. Users can modify the existing functions, add new analysis steps, or extend the pipeline with custom code. This feature makes it very flexible, enabling users to adapt the pipeline for different research projects or data types. 
